import type { Metadata } from "next";
import { Flex, Text, Theme } from "@radix-ui/themes";
import "./globals.css";
import { Merriweather_Sans, Rubik } from 'next/font/google'

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

const merriweatherSans = Merriweather_Sans({
  variable: '--font-merriweather-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Dale's List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweatherSans.variable} ${rubik.variable} antialiased`}
      >
        <Theme
          accentColor="jade"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="full"
        >
          {children}
          <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
            <Flex gap="3">
              <Text>Copyright &copy; 2025</Text>
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://github.com/dalecb13"
                target="_blank"
                rel="noopener noreferrer"
              >
                Dale Chang
              </a>
              
            </Flex>
          </footer>
        </Theme>
      </body>
    </html>
  );
}
