import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import { Merriweather_Sans, Rubik } from 'next/font/google'

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

const merriweatherSans = Merriweather_Sans({
  variable: '--font-merriweather-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Dale's List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweatherSans.variable} ${rubik.variable} antialiased`}
      >
        <Theme
          accentColor="jade"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="full"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
